user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
