# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                default_target_path: /backoffice
                login_path: /backoffice/login
                check_path: /backoffice/login_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: /backoffice/logout
                target: /backoffice/login

            logout_on_user_change: true
            
            anonymous:    true
            #remember_me:
            #    key: %secret%

    access_control:
        - { path: ^/backoffice/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice, role: ROLE_ADMIN }
