<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBiup5c5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBiup5c5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBiup5c5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBiup5c5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBiup5c5\appProdProjectContainer(array(
    'container.build_hash' => 'Biup5c5',
    'container.build_id' => 'c0aa553c',
    'container.build_time' => 1528995494,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBiup5c5');
