main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Index:index }

#fiche lunette
main_fichepage:
    path:     /lunette/{id}/fiche.html
    defaults: { _controller: MainBundle:Fiche:fiche }

#inscription client
main_inscriptionpage:
    path:     /lunette/{id}/inscription.html
    defaults: { _controller: MainBundle:Fiche:inscription }

#mon panier
main_panierpage:
    path:     /lunette/mon-panier.html
    defaults: { _controller: MainBundle:Fiche:panier }

#add produit panier
main_panierpage_ajout:
    path:     /lunette/{id}/ajout-panier.html
    defaults: { _controller: MainBundle:Fiche:panierAdd }

#delete panier
main_panierpage_delete:
    path:     /lunette/{id}/delete-panier.html
    defaults: { _controller: MainBundle:Fiche:panierDelete }

#valider commande
main_validerCommandepage:
    path:     /lunette/valider-commande.html
    defaults: { _controller: MainBundle:Fiche:validerCommande }
