<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'common.flashBag' shared service.

include_once $this->targetDirs[3].'/src/BackOfficeBundle/Services/Common/CommonService.php';

return $this->services['common.flashBag'] = new \BackOfficeBundle\Services\Common\CommonService(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'});
