<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'main.panier' shared service.

include_once $this->targetDirs[3].'/src/MainBundle/Services/Panier/PanierService.php';

return $this->services['main.panier'] = new \MainBundle\Services\Panier\PanierService(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'});
