backoffice_lignecommande_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:LigneCommande:index" }
    methods:  GET

backoffice_lignecommande_show:
    path:     /{id}/show
    defaults: { _controller: "BackOfficeBundle:LigneCommande:show" }
    methods:  GET

backoffice_lignecommande_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:LigneCommande:new" }
    methods:  [GET, POST]

backoffice_lignecommande_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackOfficeBundle:LigneCommande:edit" }
    methods:  [GET, POST]

backoffice_lignecommande_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackOfficeBundle:LigneCommande:deleteElement" }
    methods:  [POST, DELETE,GET]
