<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFi5dtwc\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFi5dtwc/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFi5dtwc.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFi5dtwc\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerFi5dtwc\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Fi5dtwc',
    'container.build_id' => '1b4b48e1',
    'container.build_time' => 1532520934,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFi5dtwc');
