<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVlavmg4\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVlavmg4/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVlavmg4.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVlavmg4\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVlavmg4\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vlavmg4',
    'container.build_id' => '9f09f96e',
    'container.build_time' => 1532528327,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVlavmg4');
