<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVggenh0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVggenh0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVggenh0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVggenh0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVggenh0\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vggenh0',
    'container.build_id' => 'f21757a6',
    'container.build_time' => 1532011737,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVggenh0');
