<?php

namespace BackOfficeBundle\Repository;

/**
 * EntreeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreeProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
