<?php

namespace BackOfficeBundle\Repository;

/**
 * MarqueProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
