<?php

namespace BackOfficeBundle\Repository;

/**
 * SortieProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
