<?php

namespace BackOfficeBundle\Repository;

/**
 * VentesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentesRepository extends \Doctrine\ORM\EntityRepository
{
}
